# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
include:

    # dummy firmware, just making sure we can build for the RP2040
  - board: sparkfun_pro_micro_rp2040
    shield: tester_pro_micro
    artifact-name: quacken_test
    cmake-args: -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap

    # Quacken Zero + SparkFun RP2040, default config
  - board: sparkfun_pro_micro_rp2040
    shield: quacken_zero
    artifact-name: quacken_zero_hrm
    cmake-args: -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap

    # Quacken Flex, default config
  - board: quacken_flex
    artifact-name: quacken_flex_hrm
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DDUAL_KEYS=HOME_ROW_MODS"

    # Quacken Flex, Vim config
  - board: quacken_flex
    artifact-name: quacken_flex_vim_shift
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DHRM_SHIFT -DDUAL_KEYS=HOME_ROW_MODS_VIM"

